name: Build, Test & Publish
on:
  
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Build
        run: dotnet build 
        working-directory: ./SamDotNet/
            
      - name: Test
        working-directory: ./SamDotNet.Tests/
        run: dotnet test 
      
      - name: Create Nuget package
        working-directory: ./SamDotNet/
        run: dotnet pack
              
      - name: Publish Nuget package
        env:
          nuget_api_key: ${{ secrets.NUGET_API_KEY }}
        working-directory: ./SamDotNet/bin/Debug/
        run: dotnet nuget push ./*.nupkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json" --skip-duplicate
      
